### ISSUE TITLE
非常不错，想使用，但是。。。。。。

### ISSUE THREAD

**Issue by hulang** [yzh52521/filesystem#1]
正在使用作者你的：https://github.com/yzh52521/thinkphp-filesystem-cloud
想使用这个，但是。。。。。。奈何thinkphp6目前league/flysystem还是1x版本。。
另外作者，你这个都集成了那么多了，能否再集成下：
https://packagist.org/packages/league/flysystem-sftp
https://packagist.org/packages/league/flysystem-ftp
你可以特别说明下集成这两个需要开启ftp扩展。。。。

**Comment by yuanzhihai** [comment]
> 正在使用作者你的：https://github.com/QThans/thinkphp-filesystem-cloud 想使用这个，但是。。。。。。奈何thinkphp6目前league/flysystem还是1x版本。。 另外作者，你这个都集成了那么多了，能否再集成下： https://packagist.org/packages/league/flysystem-sftp https://packagist.org/packages/league/flysystem-ftp 你可以特别说明下集成这两个需要开启ftp扩展。。。。

https://github.com/QThans/thinkphp-filesystem-cloud
这个扩展不是我写
你可以给作者留言

**Comment by hulang** [comment]
@yzh52521 https://github.com/yzh52521/thinkphp-filesystem-cloud
是你的这个扩展，哈哈，发错了。。
目前https://github.com/yzh52521/filesystem，作者哥们，你能否加上
https://packagist.org/packages/league/flysystem-sftp
https://packagist.org/packages/league/flysystem-ftp
你可以特别说明下集成这两个需要开启ftp扩展。。。。
